version: "3.8"
networks:
  database_network:
    driver: bridge
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER:  ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database_network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    depends_on:
      - postgres
    networks:
      - database_network
volumes:
  postgres_data: